name: deploy

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: check hugo version
      run: hugo version

    - name: echo working directory
      run: echo ${{ github.workspace }}

    - name: build
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -l
        hugo -D
        ls -l public

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
